apiVersion: amtd.r6security.com/v1beta1
kind: AdaptiveMovingTargetDefense
metadata:
  labels:
    app.kubernetes.io/name: adaptivemovingtargetdefense
    app.kubernetes.io/instance: adaptivemovingtargetdefense-sample
  name: amtd-demo
  namespace: demo-page
spec:
  podSelector:
    app: demo-page
  strategy:
    - rule: 
        type: default
      action:
        disable: {}
    - rule: 
        type: timed
        threatLevel: info
        source: TimeBasedTrigger
      action:
        delete: {}