---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amtd.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "amtd.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.amtd.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "amtd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        {{- include "amtd.labels" . | nindent 8 }}
        control-plane: controller-manager
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: {{ include "amtd.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.amtd.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: "{{ .Values.amtd.image.repository }}:{{ .Values.amtd.image.tag }}"
          imagePullPolicy: {{ .Values.amtd.image.pullPolicy | quote }}
          command:
            - /manager
          args:
            - --health-probe-bind-address={{ .Values.amtd.healthProbeBindAddress }}
            - --metrics-bind-address={{ .Values.amtd.metricsBindAddress }}
            - --leader-elect
          livenessProbe:
            httpGet:
              path: {{ .Values.amtd.livenessProbe.path }}
              port: {{ .Values.amtd.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.amtd.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.amtd.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.amtd.readinessProbe.path }}
              port: {{ .Values.amtd.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.amtd.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.amtd.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.amtd.resources | nindent 12 }}
          {{- with .Values.amtd.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.amtd.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.amtd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.amtd.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.amtd.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with  .Values.amtd.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
