---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - amtd.r6security.com
  resources:
  - adaptivemovingtargetdefenses
  - securityevents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - amtd.r6security.com
  resources:
  - adaptivemovingtargetdefenses/finalizers
  - securityevents/finalizers
  verbs:
  - update
- apiGroups:
  - amtd.r6security.com
  resources:
  - adaptivemovingtargetdefenses/status
  - securityevents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - watch
