nameOverride: ""
fullnameOverride: ""

amtd:
  replicaCount: 1
  image:
    repository: ghcr.io/r6security/phoenix/amtd-operator
    tag: v0.2.2
    pullPolicy: IfNotPresent

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

  terminationGracePeriodSeconds: 10

  healthProbeBindAddress: ":8081"
  metricsBindAddress: "127.0.0.1:8080"

  livenessProbe:
    path: /healthz
    port: 8081
    initialDelaySeconds: 15
    periodSeconds: 20

  readinessProbe:
    path: /readyz
    port: 8081
    initialDelaySeconds: 5
    periodSeconds: 10

  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  topologySpreadConstraints: []
  imagePullSecrets: []
